# The version property is now optional in modern Docker Compose
# version: '3.8'

name: wwebjs-api

services:
  api:
    image: avoylenko/wwebjs-api:latest
    container_name: wwebjs-api
    restart: unless-stopped

    ports:
      - "${PORT:-3000}:3000"

    env_file: .env

    volumes:
      - ./sessions:/usr/src/app/sessions

    extra_hosts:
      - "host.docker.internal:host-gateway"
